name: 福知山市イベント自動投稿

on:
  schedule:
    # 毎日午前7時（日本時間）に実行 (UTC時間で22時)
    - cron: '0 22 * * *'
  workflow_dispatch:  # 手動実行も可能

jobs:
  post-events:
    runs-on: ubuntu-latest
    
    steps:
    - name: リポジトリをチェックアウト
      uses: actions/checkout@v4
    
    - name: Python環境をセットアップ
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: 依存関係をインストール
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 tweepy
    
    - name: イベント投稿スクリプトを実行
      env:
        X_API_KEY: ${{ secrets.X_API_KEY }}
        X_API_SECRET: ${{ secrets.X_API_SECRET }}
        X_ACCESS_TOKEN: ${{ secrets.X_ACCESS_TOKEN }}
        X_ACCESS_SECRET: ${{ secrets.X_ACCESS_SECRET }}
      run: |
        python get_events.py
